### ISSUE TITLE
Refactor to use react-navigation

### ISSUE THREAD

**Issue by sibelius** [react-brasil/reactconfbr-app#23]

**Comment by joaoeffting** [comment]
I can take a look at this issue.

**Comment by sibelius** [comment]
go for it \o/

**Comment by joaoeffting** [comment]
PR made

https://github.com/react-brasil/reactconfbr-app/pull/24

**Comment by joaoeffting** [comment]
Can I open an Issue to apply Flowtype to the components?

**Comment by sibelius** [comment]
Yep please
