### ISSUE TITLE
Apply Flow to components

### ISSUE THREAD

**Issue by joaoeffting** [react-brasil/reactconfbr-app#25]
Apply Flowtype to components

**Comment by joaoeffting** [comment]
Done https://github.com/react-brasil/reactconfbr-app/pull/26

**Comment by joaoeffting** [comment]
Should I reopen this one? I was taking a look and seems like there is a lot of new components without the flowtype. Maybe we can put some hooks after all components are with flow?

**Comment by jgcmarins** [comment]
https://github.com/react-brasil/reactconfbr-app/issues/59
