### ISSUE TITLE
App sem comunicação com o Server

### ISSUE THREAD

**Issue by gregoryfm** [react-brasil/reactconfbr-app#58]
Caros,
Baixei o projeto para começar a contribuir, porém estou com um problema que não consigo resolver.

Estou com os dois projetos rodando (reactconfbr-app e reactconfbr-server), mongod e redis-server.

O que acontece é que o app sempre mostra a mensagem `Verifique sua conexão com a internet e tente de novo` quando tento criar uma conta.

![print](https://user-images.githubusercontent.com/137143/41240820-cbbf6da2-6d71-11e8-87e5-fe4a8f9d385f.png)

Minha configuração:
SO: Arch Linux
AVD: Android: 8.1 e Emulador: Nexus_4_API_27
Genymotion: Android: 8.0 e Samsung_Galaxy_S7_API_26

Estou esquecendo de algo, alguma configuração?

Obrigado.

**Comment by joao-alberto** [comment]
@gregoryfm Tenta rodar isso aqui antes `adb reverse tcp:8081 tcp:8081`

ou então muda de `localhost` para o seu ip aqui nessa [linha](https://github.com/react-brasil/reactconfbr-app/blob/6c6a8b0e240ca9d861bf484cc87d57e144189b77/src/createRelayEnvironment.js#L15)

**Comment by gregoryfm** [comment]
@joao-alberto Deu certo colocando o meu ip no `createRelayEnvironment.js`. :+1: 

Muito obrigado.

**Comment by gregoryfm** [comment]
@joao-alberto Deu certo colocando o meu ip no `createRelayEnvironment.js`. :+1: 

Muito obrigado.

**Comment by joao-alberto** [comment]
@jaburcodes @lXSPandora acho que seria ideal colocar isso numa .env pra não precisar ficar alterando no código

**Comment by jaburcodes** [comment]
@joao-alberto contribuições são mais que bem vindas, por favor.
